[package]
name = "render-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
euc = "0.5.3"
vek = "0.14.1"
minifb = "0.23.0"
